# Generated by Django 5.2.5 on 2025-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farmer_name', models.CharField(max_length=20)),
                ('f_state', models.CharField(max_length=20)),
                ('f_district', models.CharField(max_length=20)),
                ('f_age', models.CharField(max_length=20)),
                ('f_contact', models.CharField(max_length=10)),
                ('f_email', models.EmailField(max_length=254)),
                ('f_crop', models.CharField(max_length=20)),
                ('f_quantity', models.IntegerField()),
            ],
        ),
    ]
